/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

import static java.lang.Short.valueOf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class forgetpass extends javax.swing.JFrame {

    /**
     * Creates new form forgetpass
     */
    public forgetpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panelpass = new javax.swing.JPanel();
        titleLabel5 = new javax.swing.JLabel();
        titleLabel6 = new javax.swing.JLabel();
        titleLabel7 = new javax.swing.JLabel();
        titleLabel8 = new javax.swing.JLabel();
        homePicLabel = new javax.swing.JLabel();
        nl = new javax.swing.JLabel();
        nameT = new javax.swing.JTextField();
        newpassL = new javax.swing.JLabel();
        changepassT = new javax.swing.JPasswordField();
        change = new javax.swing.JButton();
        loginTLabel = new javax.swing.JLabel();
        loginExitButton = new javax.swing.JButton();
        backButtonIncome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 104, 138));
        jPanel1.setLayout(null);

        Panelpass.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel5.setText("BOOK ORDER");

        titleLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel6.setText("PROCESS");

        titleLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel7.setText("MANAGEMENT");

        titleLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel8.setText("SYSTEM");

        homePicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        homePicLabel.setToolTipText("");

        javax.swing.GroupLayout PanelpassLayout = new javax.swing.GroupLayout(Panelpass);
        Panelpass.setLayout(PanelpassLayout);
        PanelpassLayout.setHorizontalGroup(
            PanelpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelpassLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(homePicLabel)
                        .addComponent(titleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        PanelpassLayout.setVerticalGroup(
            PanelpassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelpassLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleLabel5)
                .addGap(31, 31, 31)
                .addComponent(titleLabel6)
                .addGap(26, 26, 26)
                .addComponent(homePicLabel)
                .addGap(39, 39, 39)
                .addComponent(titleLabel7)
                .addGap(18, 18, 18)
                .addComponent(titleLabel8)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1.add(Panelpass);
        Panelpass.setBounds(0, 0, 240, 500);

        nl.setBackground(new java.awt.Color(0, 0, 0));
        nl.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        nl.setForeground(new java.awt.Color(255, 255, 255));
        nl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nl.setText("Name:");
        nl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nl.setRequestFocusEnabled(false);
        jPanel1.add(nl);
        nl.setBounds(310, 140, 94, 25);

        nameT.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        nameT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        nameT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTKeyReleased(evt);
            }
        });
        jPanel1.add(nameT);
        nameT.setBounds(330, 170, 211, 29);

        newpassL.setBackground(new java.awt.Color(0, 0, 0));
        newpassL.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        newpassL.setForeground(new java.awt.Color(255, 255, 255));
        newpassL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newpassL.setText("New Password:");
        newpassL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newpassL.setRequestFocusEnabled(false);
        jPanel1.add(newpassL);
        newpassL.setBounds(330, 280, 140, 19);

        changepassT.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        changepassT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        changepassT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        changepassT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                changepassTKeyReleased(evt);
            }
        });
        jPanel1.add(changepassT);
        changepassT.setBounds(330, 310, 211, 29);

        change.setBackground(new java.awt.Color(255, 255, 255));
        change.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        change.setText("CHANGE");
        change.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        change.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                changeMouseReleased(evt);
            }
        });
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        change.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                changeKeyReleased(evt);
            }
        });
        jPanel1.add(change);
        change.setBounds(370, 400, 140, 30);

        loginTLabel.setBackground(new java.awt.Color(0, 0, 0));
        loginTLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        loginTLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTLabel.setText("Change Password");
        loginTLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginTLabel.setRequestFocusEnabled(false);
        jPanel1.add(loginTLabel);
        loginTLabel.setBounds(260, 50, 330, 48);

        loginExitButton.setBackground(new java.awt.Color(255, 255, 255));
        loginExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        loginExitButton.setText("X");
        loginExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        loginExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        loginExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        loginExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginExitButton);
        loginExitButton.setBounds(583, 0, 50, 30);

        backButtonIncome.setBackground(new java.awt.Color(255, 255, 255));
        backButtonIncome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        backButtonIncome.setText("<");
        backButtonIncome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButtonIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonIncomeActionPerformed(evt);
            }
        });
        jPanel1.add(backButtonIncome);
        backButtonIncome.setBounds(240, 0, 60, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(634, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_nameTKeyReleased

    private void changepassTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changepassTKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_changepassTKeyReleased

    private void changeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_changeMouseReleased

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        // TODO add your handling code here:
        String name = nameT.getText();
        String changepass = changepassT.getText(); 
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
                .getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
                            + "selectMethod=cursor", "sa", "123456");

            String sql = "Update admin set adminPassword="+changepass+
                        " where adminName = '"+name+"'";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.executeUpdate();
                
         
            JOptionPane.showMessageDialog(null, "password changed");
            this.setVisible(false);
            
            new loginAdmin().setVisible(true);


        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_changeActionPerformed

    private void changeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_changeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_changeKeyReleased

    private void loginExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_loginExitButtonActionPerformed

    private void backButtonIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonIncomeActionPerformed
        // TODO add your handling code here:
        loginAdmin loginAdmin = new loginAdmin();
        loginAdmin . setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgetpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgetpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelpass;
    private javax.swing.JButton backButtonIncome;
    private javax.swing.JButton change;
    private javax.swing.JPasswordField changepassT;
    private javax.swing.JLabel homePicLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginExitButton;
    private javax.swing.JLabel loginTLabel;
    private javax.swing.JTextField nameT;
    private javax.swing.JLabel newpassL;
    private javax.swing.JLabel nl;
    private javax.swing.JLabel titleLabel5;
    private javax.swing.JLabel titleLabel6;
    private javax.swing.JLabel titleLabel7;
    private javax.swing.JLabel titleLabel8;
    // End of variables declaration//GEN-END:variables
}
