/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

/**
 *
 * @author user
 */
public class homePage extends javax.swing.JFrame {
    

    /**
     * Creates new form homePage
     */
    public homePage() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePagePanel = new javax.swing.JPanel();
        homePanelWhite = new javax.swing.JPanel();
        titleLabel5 = new javax.swing.JLabel();
        titleLabel6 = new javax.swing.JLabel();
        homePicLabel1 = new javax.swing.JLabel();
        titleLabel7 = new javax.swing.JLabel();
        titleLabel8 = new javax.swing.JLabel();
        homeTLabel = new javax.swing.JLabel();
        homeExitButton = new javax.swing.JButton();
        booksButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        suppliersButton = new javax.swing.JButton();
        incomeButton = new javax.swing.JButton();
        perSuppliesButton = new javax.swing.JButton();
        perOrderButton = new javax.swing.JButton();
        backButtonHome = new javax.swing.JButton();
        bookSale = new javax.swing.JButton();
        backButtonHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        homePagePanel.setBackground(new java.awt.Color(85, 104, 138));
        homePagePanel.setForeground(new java.awt.Color(255, 255, 255));
        homePagePanel.setLayout(null);

        homePanelWhite.setBackground(new java.awt.Color(255, 255, 255));
        homePanelWhite.setLayout(null);

        titleLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel5.setText("BOOK ORDER");
        homePanelWhite.add(titleLabel5);
        titleLabel5.setBounds(30, 40, 161, 33);

        titleLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel6.setText("PROCESS");
        homePanelWhite.add(titleLabel6);
        titleLabel6.setBounds(60, 90, 102, 33);

        homePicLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        homePicLabel1.setToolTipText("");
        homePanelWhite.add(homePicLabel1);
        homePicLabel1.setBounds(30, 160, 170, 170);

        titleLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel7.setText("MANAGEMENT");
        homePanelWhite.add(titleLabel7);
        titleLabel7.setBounds(20, 380, 184, 33);

        titleLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel8.setText("SYSTEM");
        homePanelWhite.add(titleLabel8);
        titleLabel8.setBounds(70, 440, 87, 33);

        homePagePanel.add(homePanelWhite);
        homePanelWhite.setBounds(0, 0, 250, 497);

        homeTLabel.setBackground(new java.awt.Color(0, 0, 0));
        homeTLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        homeTLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTLabel.setText("Home");
        homeTLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeTLabel.setRequestFocusEnabled(false);
        homePagePanel.add(homeTLabel);
        homeTLabel.setBounds(370, 60, 140, 48);

        homeExitButton.setBackground(new java.awt.Color(255, 255, 255));
        homeExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        homeExitButton.setText("X");
        homeExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        homeExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        homeExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        homeExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeExitButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(homeExitButton);
        homeExitButton.setBounds(583, 0, 50, 30);

        booksButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        booksButton.setText("Books");
        booksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(booksButton);
        booksButton.setBounds(290, 130, 120, 40);

        customersButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        customersButton.setLabel("Customers");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(customersButton);
        customersButton.setBounds(440, 130, 120, 40);

        suppliersButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        suppliersButton.setText("Suppliers");
        suppliersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(suppliersButton);
        suppliersButton.setBounds(440, 260, 120, 40);

        incomeButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        incomeButton.setText("Income");
        incomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomeButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(incomeButton);
        incomeButton.setBounds(290, 330, 120, 40);

        perSuppliesButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        perSuppliesButton.setLabel("Supplies");
        perSuppliesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perSuppliesButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(perSuppliesButton);
        perSuppliesButton.setBounds(440, 190, 120, 40);

        perOrderButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        perOrderButton.setText("Orders");
        perOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perOrderButtonActionPerformed(evt);
            }
        });
        homePagePanel.add(perOrderButton);
        perOrderButton.setBounds(290, 260, 120, 40);

        backButtonHome.setBackground(new java.awt.Color(255, 255, 255));
        backButtonHome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        backButtonHome.setText("<");
        backButtonHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonHomeActionPerformed(evt);
            }
        });
        homePagePanel.add(backButtonHome);
        backButtonHome.setBounds(517, 438, 60, 32);

        bookSale.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        bookSale.setText("Book Sell");
        bookSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSaleActionPerformed(evt);
            }
        });
        homePagePanel.add(bookSale);
        bookSale.setBounds(290, 190, 120, 40);
        bookSale.getAccessibleContext().setAccessibleName("bookSale");

        backButtonHome1.setBackground(new java.awt.Color(255, 255, 255));
        backButtonHome1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        backButtonHome1.setText("Add Admin?");
        backButtonHome1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButtonHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonHome1ActionPerformed(evt);
            }
        });
        homePagePanel.add(backButtonHome1);
        backButtonHome1.setBounds(440, 330, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(634, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_homeExitButtonActionPerformed

    private void backButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonHomeActionPerformed
        // TODO add your handling code here:
        loginAdmin loginAdmin = new loginAdmin();
        loginAdmin . setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonHomeActionPerformed

    private void perSuppliesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perSuppliesButtonActionPerformed
        // TODO add your handling code here:
        bookSupplies bookSupplies = new bookSupplies();
        bookSupplies.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perSuppliesButtonActionPerformed

    private void booksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksButtonActionPerformed
        // TODO add your handling code here:
        books books = new books();
        books.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_booksButtonActionPerformed

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        // TODO add your handling code here:
        customers customers = new customers();
        customers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customersButtonActionPerformed

    private void incomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeButtonActionPerformed
        // TODO add your handling code here:
        income incomeProfit = new income();
        incomeProfit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_incomeButtonActionPerformed

    private void perOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perOrderButtonActionPerformed
        // TODO add your handling code here:
        orders bookOrder = new orders();
        bookOrder.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_perOrderButtonActionPerformed

    private void suppliersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersButtonActionPerformed
        // TODO add your handling code here:
        suppliers suppliers = new suppliers();
        suppliers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_suppliersButtonActionPerformed

    private void bookSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSaleActionPerformed
        // TODO add your handling code here:
        bookSell bookSell = new bookSell();
        bookSell.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookSaleActionPerformed

    private void backButtonHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonHome1ActionPerformed
        // TODO add your handling code here:
        form form = new form();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButtonHome;
    private javax.swing.JButton backButtonHome1;
    private javax.swing.JButton bookSale;
    private javax.swing.JButton booksButton;
    private javax.swing.JButton customersButton;
    private javax.swing.JButton homeExitButton;
    private javax.swing.JPanel homePagePanel;
    private javax.swing.JPanel homePanelWhite;
    private javax.swing.JLabel homePicLabel1;
    private javax.swing.JLabel homeTLabel;
    private javax.swing.JButton incomeButton;
    private javax.swing.JButton perOrderButton;
    private javax.swing.JButton perSuppliesButton;
    private javax.swing.JButton suppliersButton;
    private javax.swing.JLabel titleLabel5;
    private javax.swing.JLabel titleLabel6;
    private javax.swing.JLabel titleLabel7;
    private javax.swing.JLabel titleLabel8;
    // End of variables declaration//GEN-END:variables
}
