/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class loginAdmin extends javax.swing.JFrame {
    
    
    public static String adminId;
    public static String adminname;

    /**
     * Creates new form loginAdmin
     */
    public loginAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        loginPanelWhite = new javax.swing.JPanel();
        titleLabel5 = new javax.swing.JLabel();
        titleLabel6 = new javax.swing.JLabel();
        titleLabel7 = new javax.swing.JLabel();
        titleLabel8 = new javax.swing.JLabel();
        homePicLabel = new javax.swing.JLabel();
        loginTLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        oasswordLabel = new javax.swing.JLabel();
        loginSubmitButton = new javax.swing.JButton();
        usernameTextField = new javax.swing.JTextField();
        psswordField = new javax.swing.JPasswordField();
        loginExitButton = new javax.swing.JButton();
        usernameNotExist = new javax.swing.JLabel();
        passNotExist = new javax.swing.JLabel();
        logIn_Notice = new javax.swing.JLabel();
        forgetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        LoginPanel.setBackground(new java.awt.Color(85, 104, 138));
        LoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        LoginPanel.setLayout(null);

        loginPanelWhite.setBackground(new java.awt.Color(255, 255, 255));

        titleLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel5.setText("BOOK ORDER");

        titleLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel6.setText("PROCESS");

        titleLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel7.setText("MANAGEMENT");

        titleLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        titleLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel8.setText("SYSTEM");

        homePicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        homePicLabel.setToolTipText("");

        javax.swing.GroupLayout loginPanelWhiteLayout = new javax.swing.GroupLayout(loginPanelWhite);
        loginPanelWhite.setLayout(loginPanelWhiteLayout);
        loginPanelWhiteLayout.setHorizontalGroup(
            loginPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelWhiteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(loginPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(homePicLabel)
                        .addComponent(titleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        loginPanelWhiteLayout.setVerticalGroup(
            loginPanelWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelWhiteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(titleLabel5)
                .addGap(31, 31, 31)
                .addComponent(titleLabel6)
                .addGap(26, 26, 26)
                .addComponent(homePicLabel)
                .addGap(39, 39, 39)
                .addComponent(titleLabel7)
                .addGap(18, 18, 18)
                .addComponent(titleLabel8))
        );

        LoginPanel.add(loginPanelWhite);
        loginPanelWhite.setBounds(0, 0, 240, 500);

        loginTLabel.setBackground(new java.awt.Color(0, 0, 0));
        loginTLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        loginTLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginTLabel.setText("Admin Log In");
        loginTLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginTLabel.setRequestFocusEnabled(false);
        LoginPanel.add(loginTLabel);
        loginTLabel.setBounds(310, 50, 250, 48);

        usernameLabel.setBackground(new java.awt.Color(0, 0, 0));
        usernameLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Name:");
        usernameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usernameLabel.setRequestFocusEnabled(false);
        LoginPanel.add(usernameLabel);
        usernameLabel.setBounds(390, 180, 94, 25);

        oasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        oasswordLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        oasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        oasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oasswordLabel.setText("Password:");
        oasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        oasswordLabel.setRequestFocusEnabled(false);
        LoginPanel.add(oasswordLabel);
        oasswordLabel.setBounds(400, 310, 94, 19);

        loginSubmitButton.setBackground(new java.awt.Color(255, 255, 255));
        loginSubmitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        loginSubmitButton.setText("SUBMIT");
        loginSubmitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginSubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginSubmitButtonMouseReleased(evt);
            }
        });
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitButtonActionPerformed(evt);
            }
        });
        loginSubmitButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginSubmitButtonKeyReleased(evt);
            }
        });
        LoginPanel.add(loginSubmitButton);
        loginSubmitButton.setBounds(410, 410, 79, 29);

        usernameTextField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        usernameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTextFieldKeyReleased(evt);
            }
        });
        LoginPanel.add(usernameTextField);
        usernameTextField.setBounds(338, 205, 211, 29);

        psswordField.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        psswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        psswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                psswordFieldKeyReleased(evt);
            }
        });
        LoginPanel.add(psswordField);
        psswordField.setBounds(340, 330, 211, 29);

        loginExitButton.setBackground(new java.awt.Color(255, 255, 255));
        loginExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        loginExitButton.setText("X");
        loginExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        loginExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        loginExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        loginExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(loginExitButton);
        loginExitButton.setBounds(583, 0, 50, 30);

        usernameNotExist.setBackground(new java.awt.Color(0, 0, 0));
        usernameNotExist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernameNotExist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(usernameNotExist);
        usernameNotExist.setBounds(340, 240, 210, 20);

        passNotExist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passNotExist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(passNotExist);
        passNotExist.setBounds(340, 370, 210, 20);

        logIn_Notice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logIn_Notice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(logIn_Notice);
        logIn_Notice.setBounds(340, 270, 210, 20);

        forgetbtn.setBackground(new java.awt.Color(255, 255, 255));
        forgetbtn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        forgetbtn.setText("Forget Password?");
        forgetbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        forgetbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        forgetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                forgetbtnMouseReleased(evt);
            }
        });
        forgetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetbtnActionPerformed(evt);
            }
        });
        forgetbtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                forgetbtnKeyReleased(evt);
            }
        });
        LoginPanel.add(forgetbtn);
        forgetbtn.setBounds(370, 450, 149, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(634, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed
        // TODO add your handling code here:
       if (usernameTextField.getText().trim().isEmpty() && psswordField.getText().trim().isEmpty())
        {
            usernameNotExist.setText("**Username is Empty!");
            passNotExist.setText("**Password is Empty!!");
            logIn_Notice.setText("");
        }
        else if (usernameTextField.getText().trim().isEmpty())
        {
            usernameNotExist.setText("**Username is Empty!");
            passNotExist.setText("");
            logIn_Notice.setText("");
        }
        else if(psswordField.getText().trim().isEmpty())
        {
            usernameNotExist.setText("");
            passNotExist.setText("**Password is Empty!!");
            logIn_Notice.setText("");
        }
        else
        {
            try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
                "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
                        + "selectMethod=cursor", "sa", "123456");

            String sql = "Select * from admin where adminName=? and adminPassword = ?";
            PreparedStatement pst = connection.prepareStatement(sql);
            pst.setString(1, usernameTextField.getText());
            pst.setString(2, psswordField.getText());
            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Welcome to your BOOK ORDER "
                        + "PROCESS MANAGEMENT SYSTEM");
                new homePage().setVisible(true);
                
                adminId = rs.getString("adminId");
                adminname = usernameTextField.getText();
                usernameTextField.setText("");
                psswordField.setText("");
                

            }
            else{
                usernameNotExist.setText("");
                passNotExist.setText("");
                usernameTextField.setText("");
                psswordField.setText("");
                logIn_Notice.setText("Incorrect Username or Password!");

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
       
       
    }//GEN-LAST:event_loginSubmitButtonActionPerformed

    private void loginExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_loginExitButtonActionPerformed

    private void usernameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTextFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_usernameTextFieldKeyReleased

    private void psswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psswordFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_psswordFieldKeyReleased

    private void loginSubmitButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginSubmitButtonKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginSubmitButtonKeyReleased

    private void loginSubmitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginSubmitButtonMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_loginSubmitButtonMouseReleased

    private void forgetbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetbtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetbtnMouseReleased

    private void forgetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetbtnActionPerformed
        // TODO add your handling code here:

        forgetpass forgetpass = new forgetpass();
        forgetpass.setVisible(true);
    }//GEN-LAST:event_forgetbtnActionPerformed

    private void forgetbtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forgetbtnKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_forgetbtnKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton forgetbtn;
    private javax.swing.JLabel homePicLabel;
    private javax.swing.JLabel logIn_Notice;
    private javax.swing.JButton loginExitButton;
    private javax.swing.JPanel loginPanelWhite;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JLabel loginTLabel;
    private javax.swing.JLabel oasswordLabel;
    private javax.swing.JLabel passNotExist;
    private javax.swing.JPasswordField psswordField;
    private javax.swing.JLabel titleLabel5;
    private javax.swing.JLabel titleLabel6;
    private javax.swing.JLabel titleLabel7;
    private javax.swing.JLabel titleLabel8;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameNotExist;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
