/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class addNewCustomer extends javax.swing.JFrame {
    
    
    Connection connection;
    public static String cusid;
    public static String cusname;
    public static String cusmail;
    public static String cusaddress;
    public static String cusphn;
    public static String custype;
    

    /**
     * Creates new form addNewCustomer
     */
    public addNewCustomer() {
        initComponents();
        generateID obj = new generateID();
        try {
            cusid = obj.generator("customer", "customerId", "C");
        } catch (SQLException ex) {
            Logger.getLogger(addNewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        cusIdT.setText(cusid);
        
    }
    
    public void connectDB() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager
            .getConnection(
             "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
               + "selectMethod=cursor", "sa", "123456");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addcusLabel = new javax.swing.JLabel();
        addCusExitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cusNameT = new javax.swing.JTextField();
        cusMailT = new javax.swing.JTextField();
        cusAddrssT = new javax.swing.JTextField();
        cusPhnT = new javax.swing.JTextField();
        cusDoneBtn = new javax.swing.JButton();
        addCus_notice = new javax.swing.JLabel();
        cusIdT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 104, 138));
        jPanel1.setLayout(null);

        addcusLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        addcusLabel.setForeground(new java.awt.Color(255, 255, 255));
        addcusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcusLabel.setText("ADD NEW CUSTOMER");
        jPanel1.add(addcusLabel);
        addcusLabel.setBounds(90, 10, 440, 40);

        addCusExitButton.setBackground(new java.awt.Color(255, 255, 255));
        addCusExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addCusExitButton.setText("X");
        addCusExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        addCusExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        addCusExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        addCusExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCusExitButton);
        addCusExitButton.setBounds(560, 10, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 130, 130, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("EMAIL:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 190, 130, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADDRESS:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 250, 130, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PHONE NO:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 310, 130, 30);
        jPanel1.add(cusNameT);
        cusNameT.setBounds(170, 130, 420, 30);

        cusMailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusMailTActionPerformed(evt);
            }
        });
        jPanel1.add(cusMailT);
        cusMailT.setBounds(170, 190, 420, 30);
        jPanel1.add(cusAddrssT);
        cusAddrssT.setBounds(170, 250, 420, 30);
        jPanel1.add(cusPhnT);
        cusPhnT.setBounds(170, 310, 420, 30);

        cusDoneBtn.setText("DONE");
        cusDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusDoneBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cusDoneBtn);
        cusDoneBtn.setBounds(40, 390, 550, 50);

        addCus_notice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addCus_notice.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(addCus_notice);
        addCus_notice.setBounds(400, 580, 260, 30);

        cusIdT.setEditable(false);
        cusIdT.setBackground(new java.awt.Color(204, 204, 204));
        cusIdT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusIdTActionPerformed(evt);
            }
        });
        jPanel1.add(cusIdT);
        cusIdT.setBounds(170, 80, 420, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Customer ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 80, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(628, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCusExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addCusExitButtonActionPerformed

    private void cusMailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusMailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusMailTActionPerformed

    private void cusDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusDoneBtnActionPerformed
        // TODO add your handling code here:
        cusname= cusNameT.getText();
        cusmail = cusMailT.getText();
        cusaddress = cusAddrssT.getText();
        cusphn = cusPhnT.getText();
        custype = "REGULAR";
      
        
        if(cusname.isEmpty() || cusmail.isEmpty() || cusaddress.isEmpty() ||
                cusphn.isEmpty()){
            
            JOptionPane.showMessageDialog(null,"Please fill all fields");
        }
        else{
            try {

                connectDB();
                String sql = "Insert into customer(customerId,customerName,customerEmail,"
                        + "customerAddress,customerPhone,"
                        + "customerType) "
                        + "values(?,?,?,?,?,?)";

                PreparedStatement pst = connection.prepareStatement(sql);
                pst.setString(1, cusid);
                pst.setString(2, cusname);
                pst.setString(3, cusmail);
                pst.setString(4, cusaddress);
                pst.setString(5, cusphn);
                pst.setString(6, custype);

                pst.executeUpdate();
             
                addCus_notice.setText("Customer is added Successfully");
                //dispose();
                

            } catch (SQLException e) {
                
            }
        }
        
        sellFinish sellFinish = new sellFinish();
        sellFinish.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cusDoneBtnActionPerformed

    private void cusIdTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusIdTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusIdTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCusExitButton;
    private javax.swing.JLabel addCus_notice;
    private javax.swing.JLabel addcusLabel;
    private javax.swing.JTextField cusAddrssT;
    private javax.swing.JButton cusDoneBtn;
    private javax.swing.JTextField cusIdT;
    private javax.swing.JTextField cusMailT;
    private javax.swing.JTextField cusNameT;
    private javax.swing.JTextField cusPhnT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
