package dbdummy;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 */
public class sellFinish extends javax.swing.JFrame {
    
    Connection connection;
    public String cusname = addNewCustomer.cusname;
    public String poid = bookSell.poid;
    public String cusid = addNewCustomer.cusid;
    public float totalprice = bookSell.totalprice;
    public String cusmail = addNewCustomer.cusmail;
    public String cusaddress = addNewCustomer.cusaddress;
    public String cusphn = addNewCustomer.cusphn;
    public String custype;
    public static boolean cusTable;
    float sub;
    float rcv;
    float chng;
    public boolean forOrder = bookSell.forOrder;
    boolean cusFound;
    
    Date date;
    Calendar c;
    String da;
    

    /**
     * Creates new form SellFinish
     */
    public sellFinish() {
        initComponents();
        totalT.setText(Float.toString(totalprice));
        float vat = (float) (totalprice*(0.05));
        vatT.setText(Float.toString(vat));
        sub = (float) (totalprice+vat);
        subtotalT.setText(Float.toString(sub));
        
        
        if(cusTable==true){
            cusidT.setText(cusid);
            cusnameT.setText(cusname);
            cusmailT.setText(cusmail);
            cusphnT.setText(cusphn);
            cusaddressT.setText(cusaddress);
            discountT.setText("0.00");
        }
        
        if(forOrder==true) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            date = new Date();
            c = Calendar.getInstance(); 
            c.setTime(date); 
            c.add(Calendar.DATE, 1);
            date = c.getTime();
            DeliveryDateT.setText(formatter.format(date));
            da = DeliveryDateT.getText();
            orderIdT.setText(poid);
        }
    }
    
  /*  
    
     public void connectDB() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
             "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
               + "selectMethod=cursor", "sa", "123456");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     */
     
     
     public void checkType(String id) throws ClassNotFoundException{
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager
            .getConnection(
             "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
               + "selectMethod=cursor", "sa", "123456");
            ///update where (select count cusid)
            ///UPDATE customer SET customerType = 'PREMIUM' WHERE 
            ///(SELECT SUM(totalIncome) From perPerchaseOrder WHERE customerId='C02') > 1111 AND customerId = 'C02'
            String sql = "UPDATE customer SET customerType = 'PREMIUM' WHERE ";
            sql = sql + "(SELECT SUM(totalIncome) From perPerchaseOrder WHERE customerId='"+id+"') >"+1111+" AND customerId = '"+id+"'";
            PreparedStatement pst = connection.prepareStatement(sql);
            int row = pst.executeUpdate();
            
            if(row==1){
                custype = "PREMIUM";
            }else if(row==0){
                
            }else {
                JOptionPane.showMessageDialog(null, "OOPS!!There's problem.");
            }

        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addcusLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cusnameT = new javax.swing.JTextField();
        cusmailT = new javax.swing.JTextField();
        cusaddressT = new javax.swing.JTextField();
        vatT = new javax.swing.JTextField();
        cusidT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        searchT = new javax.swing.JTextField();
        checkBtn = new javax.swing.JButton();
        discountT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        subtotalT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rcvamountT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        chngT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cusphnT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        totalT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        finishBtn = new javax.swing.JButton();
        addcusBtn = new javax.swing.JButton();
        updateInfoBtn = new javax.swing.JButton();
        orderIdT = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        DeliveryDateT = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 104, 138));
        jPanel1.setLayout(null);

        addcusLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        addcusLabel.setForeground(new java.awt.Color(255, 255, 255));
        addcusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcusLabel.setText("Finish Sell");
        jPanel1.add(addcusLabel);
        addcusLabel.setBounds(220, 10, 310, 40);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 150, 140, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("EMAIL:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 190, 140, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("ADDRESS:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 230, 140, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Vat:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 480, 230, 30);

        cusnameT.setEditable(false);
        cusnameT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(cusnameT);
        cusnameT.setBounds(220, 150, 470, 30);

        cusmailT.setEditable(false);
        cusmailT.setBackground(new java.awt.Color(204, 204, 204));
        cusmailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusmailTActionPerformed(evt);
            }
        });
        jPanel1.add(cusmailT);
        cusmailT.setBounds(220, 190, 470, 30);

        cusaddressT.setEditable(false);
        cusaddressT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(cusaddressT);
        cusaddressT.setBounds(220, 230, 470, 30);

        vatT.setEditable(false);
        vatT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(vatT);
        vatT.setBounds(330, 480, 360, 30);

        cusidT.setEditable(false);
        cusidT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(cusidT);
        cusidT.setBounds(220, 110, 470, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Customer Id:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 110, 140, 30);

        searchT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTActionPerformed(evt);
            }
        });
        searchT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTKeyReleased(evt);
            }
        });
        jPanel1.add(searchT);
        searchT.setBounds(220, 60, 220, 30);

        checkBtn.setText("CHECK");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });
        jPanel1.add(checkBtn);
        checkBtn.setBounds(610, 60, 80, 30);

        discountT.setEditable(false);
        discountT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(discountT);
        discountT.setBounds(330, 430, 360, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Discount:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 430, 230, 30);

        subtotalT.setEditable(false);
        subtotalT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(subtotalT);
        subtotalT.setBounds(330, 530, 360, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Sub Total:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 530, 230, 30);

        rcvamountT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rcvamountTKeyReleased(evt);
            }
        });
        jPanel1.add(rcvamountT);
        rcvamountT.setBounds(330, 580, 360, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Amount Received:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 580, 230, 30);

        chngT.setEditable(false);
        chngT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(chngT);
        chngT.setBounds(330, 630, 360, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Change:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 630, 230, 30);

        cusphnT.setEditable(false);
        cusphnT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(cusphnT);
        cusphnT.setBounds(220, 270, 470, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("search phone no.");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(20, 60, 190, 30);

        totalT.setEditable(false);
        totalT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(totalT);
        totalT.setBounds(330, 380, 360, 30);

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Total:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(60, 380, 230, 30);

        finishBtn.setText("FINISH");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });
        jPanel1.add(finishBtn);
        finishBtn.setBounds(60, 740, 630, 50);

        addcusBtn.setText("ADD NEW Cutomer");
        addcusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcusBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addcusBtn);
        addcusBtn.setBounds(220, 310, 130, 40);

        updateInfoBtn.setText("Update Info");
        jPanel1.add(updateInfoBtn);
        updateInfoBtn.setBounds(560, 310, 130, 40);

        orderIdT.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        orderIdT.setForeground(new java.awt.Color(255, 0, 51));
        orderIdT.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(orderIdT);
        orderIdT.setBounds(390, 310, 140, 40);

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("PHONE NO:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 270, 140, 30);

        jLabel19.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Delivery Date:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(60, 680, 230, 30);

        DeliveryDateT.setEditable(false);
        DeliveryDateT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(DeliveryDateT);
        DeliveryDateT.setBounds(330, 680, 360, 30);

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(460, 60, 130, 30);

        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(730, 90, 340, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1107, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1107, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cusmailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusmailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusmailTActionPerformed

    private void searchTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_searchTActionPerformed

    private void searchTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTKeyReleased
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_searchTKeyReleased

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager
            .getConnection(
             "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
               + "selectMethod=cursor", "sa", "123456");
            if(forOrder==false){
                String sql = "UPDATE perPerchaseOrder SET customerId='"+cusid+"' , totalIncome="+sub+
                            " WHERE poId = '"+poid+"'";
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.executeUpdate();
            } else {
                String sql = "UPDATE perPerchaseOrder SET customerId='"+cusid+"' , totalIncome="+sub+"' , deliveryDate=DATEADD(DAY,1,GETDATE()), deliveredOrNot="+0+
                            " WHERE poId = '"+poid+"'";
                
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.executeUpdate();
                
            }
            
            JOptionPane.showMessageDialog(null, "Successful!");
            
                 receipt.append("\tSELL DETAILS\n\n"
            +"==========================================="
            +"\nCustomer ID:\t\t\t"+cusidT.getText()+
            "\nCustomer Phone No:\t\t"+cusphnT.getText()+
             "\nDelivery Date:\t\t\t"+DeliveryDateT.getText()+

            "\nDiscount:\t\t\t"+discountT.getText()+
            "\nVat:\t\t\t"+vatT.getText()+
            "\nAmount Recieved:\t\t\t"+rcvamountT.getText()+
            "\nCharged:\t\t\t"+chngT.getText()+
            
            "\nTotal Amount:\t\t\t"+totalT.getText()
                + "\n-----------------------------------------------"
                + "By 58_61_68");

            receipt.print();
        
        } catch (ClassNotFoundException | SQLException e) {
        } catch (PrinterException ex) {
            Logger.getLogger(sellFinish.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        bookSell bookSell = new bookSell();
        bookSell.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_finishBtnActionPerformed

    private void addcusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcusBtnActionPerformed
        // TODO add your handling code here:
        cusTable = true;
        addNewCustomer addNewCustomer = new addNewCustomer();
        addNewCustomer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addcusBtnActionPerformed

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
        try {
            // TODO add your handling code here:
            
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager
                .getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=dbBOPMS;"
                            + "selectMethod=cursor", "sa", "123456");
            String cusphnsrc = searchT.getText();
            String sql = "SELECT customerId, customerName, customerEmail, customerAddress, customerPhone, customerType FROM customer" +
                            " WHERE customerPhone='"+cusphnsrc+"'";

            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                cusFound = true;
                orderIdT.setText("Found");
                cusid = rs.getString("customerId");
                cusname = rs.getString("customerName");
                cusmail = rs.getString("customerEmail");
                cusaddress = rs.getString("customerAddress");
                cusphn = rs.getString("customerPhone");
                custype = rs.getString("customerType");
                checkType(cusid);
            }
            if(cusFound==true){
                if(custype=="PREMIUM"){
                float dis = (float) (totalprice*(0.05));
                discountT.setText(Float.toString(dis));
                sub = (float) (sub-dis);
                subtotalT.setText(Float.toString(sub));
                }else{
                    discountT.setText("0.00");
                }
                cusidT.setText(cusid);
                cusnameT.setText(cusname);
                cusmailT.setText(cusmail);
                cusphnT.setText(cusphn);
                cusaddressT.setText(cusaddress);
            } else {
                orderIdT.setText("Not Found");
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(sellFinish.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(sellFinish.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_checkBtnActionPerformed

    private void rcvamountTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rcvamountTKeyReleased
        // TODO add your handling code here:
        
        rcv = Float.parseFloat(rcvamountT.getText());
        chng = (float) (rcv-sub);
        chngT.setText(Float.toString(chng));
    }//GEN-LAST:event_rcvamountTKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sellFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sellFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sellFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sellFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sellFinish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DeliveryDateT;
    private javax.swing.JButton addcusBtn;
    private javax.swing.JLabel addcusLabel;
    private javax.swing.JButton checkBtn;
    private javax.swing.JTextField chngT;
    private javax.swing.JTextField cusaddressT;
    private javax.swing.JTextField cusidT;
    private javax.swing.JTextField cusmailT;
    private javax.swing.JTextField cusnameT;
    private javax.swing.JTextField cusphnT;
    private javax.swing.JTextField discountT;
    private javax.swing.JButton finishBtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderIdT;
    private javax.swing.JTextField rcvamountT;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTextField searchT;
    private javax.swing.JTextField subtotalT;
    private javax.swing.JTextField totalT;
    private javax.swing.JButton updateInfoBtn;
    private javax.swing.JTextField vatT;
    // End of variables declaration//GEN-END:variables
}
