/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 
 */
public class SupplyFinish extends javax.swing.JFrame {
    
    
    public String sprid = addSupplier.rid;
    public String sprname = addSupplier.sprname;
    public String sprmail = addSupplier.sprmail;
    public String sprphn = addSupplier.sprphn;
    boolean sprTable;
    

    /**
     * Creates new form SupplyFinish
     */
    public SupplyFinish() {
        initComponents();
        
        if(sprTable==true){
            searchT.setText(sprid);
            suplrnameT.setText(sprname);
            suplrmailT.setText(sprmail);
            suplrphnT.setText(sprphn);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addcusLabel = new javax.swing.JLabel();
        addCusExitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        suplrnameT = new javax.swing.JTextField();
        suplrmailT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        backButtonCustomers = new javax.swing.JButton();
        searchT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        subtotalT = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paidT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dueT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        suplrphnT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        calcuBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 104, 138));
        jPanel1.setLayout(null);

        addcusLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        addcusLabel.setForeground(new java.awt.Color(255, 255, 255));
        addcusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcusLabel.setText("Finish Supply");
        jPanel1.add(addcusLabel);
        addcusLabel.setBounds(270, 10, 260, 40);

        addCusExitButton.setBackground(new java.awt.Color(255, 255, 255));
        addCusExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addCusExitButton.setText("X");
        addCusExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        addCusExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        addCusExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        addCusExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCusExitButton);
        addCusExitButton.setBounds(700, 0, 60, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NAME:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 150, 140, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("EMAIL:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 190, 140, 30);

        suplrnameT.setEditable(false);
        suplrnameT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(suplrnameT);
        suplrnameT.setBounds(220, 150, 470, 30);

        suplrmailT.setEditable(false);
        suplrmailT.setBackground(new java.awt.Color(204, 204, 204));
        suplrmailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suplrmailTActionPerformed(evt);
            }
        });
        jPanel1.add(suplrmailT);
        suplrmailT.setBounds(220, 190, 470, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Supplier ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 60, 140, 30);

        backButtonCustomers.setBackground(new java.awt.Color(255, 255, 255));
        backButtonCustomers.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        backButtonCustomers.setText("<");
        backButtonCustomers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButtonCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(backButtonCustomers);
        backButtonCustomers.setBounds(0, 0, 60, 32);

        searchT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTActionPerformed(evt);
            }
        });
        searchT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTKeyReleased(evt);
            }
        });
        jPanel1.add(searchT);
        searchT.setBounds(220, 60, 210, 30);

        jButton1.setText("CHECK");
        jPanel1.add(jButton1);
        jButton1.setBounds(610, 60, 80, 30);

        subtotalT.setEditable(false);
        subtotalT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(subtotalT);
        subtotalT.setBounds(330, 430, 360, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Sub Total:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 430, 230, 30);
        jPanel1.add(paidT);
        paidT.setBounds(330, 480, 360, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Amount Paid:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 480, 230, 30);

        dueT.setEditable(false);
        dueT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(dueT);
        dueT.setBounds(330, 590, 360, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Amount Due:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 590, 230, 30);

        suplrphnT.setEditable(false);
        suplrphnT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(suplrphnT);
        suplrphnT.setBounds(220, 230, 470, 30);

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("PHONE NO:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 230, 140, 30);

        calcuBtn.setText("CALCULATE");
        jPanel1.add(calcuBtn);
        calcuBtn.setBounds(60, 530, 630, 40);

        finishBtn.setText("FINISH");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });
        jPanel1.add(finishBtn);
        finishBtn.setBounds(60, 640, 630, 50);

        update.setText("Update Info");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update);
        update.setBounds(560, 290, 130, 40);

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Found/not");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(460, 60, 130, 30);

        add.setText("ADD NEW Supplier");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(220, 290, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(756, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCusExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addCusExitButtonActionPerformed

    private void suplrmailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suplrmailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suplrmailTActionPerformed

    private void backButtonCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonCustomersActionPerformed
        // TODO add your handling code here:
        homePage homePage = new homePage();
        homePage . setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonCustomersActionPerformed

    private void searchTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTActionPerformed

    private void searchTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchTKeyReleased

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        sprTable = true;
        addSupplier addSupplier = new addSupplier();
        addSupplier.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        updateSupplier updateSupplier = new updateSupplier();
        updateSupplier.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_updateActionPerformed

    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        // TODO add your handling code here:
        bookSupplies bookSupplies = new bookSupplies();
        bookSupplies.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_finishBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplyFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplyFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplyFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplyFinish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplyFinish().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addCusExitButton;
    private javax.swing.JLabel addcusLabel;
    private javax.swing.JButton backButtonCustomers;
    private javax.swing.JButton calcuBtn;
    private javax.swing.JTextField dueT;
    private javax.swing.JButton finishBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField paidT;
    private javax.swing.JTextField searchT;
    private javax.swing.JTextField subtotalT;
    private javax.swing.JTextField suplrmailT;
    private javax.swing.JTextField suplrnameT;
    private javax.swing.JTextField suplrphnT;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
