package dbdummy;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author 
 */
public class updateSupplier extends javax.swing.JFrame {

    /**
     * Creates new form updateSupplier
     */
    public updateSupplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addcusLabel1 = new javax.swing.JLabel();
        addCusExitButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        upsuplrnameT = new javax.swing.JTextField();
        upsuplrmailT = new javax.swing.JTextField();
        upsuplrphnT = new javax.swing.JTextField();
        upsuplrsubmitBtn = new javax.swing.JButton();
        addCus_notice1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        upsuplridT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(85, 104, 138));
        jPanel2.setLayout(null);

        addcusLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        addcusLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addcusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcusLabel1.setText("Update Supplier Info");
        jPanel2.add(addcusLabel1);
        addcusLabel1.setBounds(90, 10, 440, 40);

        addCusExitButton1.setBackground(new java.awt.Color(255, 255, 255));
        addCusExitButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addCusExitButton1.setText("X");
        addCusExitButton1.setMaximumSize(new java.awt.Dimension(10, 19));
        addCusExitButton1.setMinimumSize(new java.awt.Dimension(10, 19));
        addCusExitButton1.setPreferredSize(new java.awt.Dimension(10, 19));
        addCusExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCusExitButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(addCusExitButton1);
        addCusExitButton1.setBounds(560, 10, 60, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NAME:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 170, 130, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EMAIL:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 230, 130, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PHONE NO:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 290, 130, 30);
        jPanel2.add(upsuplrnameT);
        upsuplrnameT.setBounds(170, 170, 420, 30);

        upsuplrmailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upsuplrmailTActionPerformed(evt);
            }
        });
        jPanel2.add(upsuplrmailT);
        upsuplrmailT.setBounds(170, 230, 420, 30);
        jPanel2.add(upsuplrphnT);
        upsuplrphnT.setBounds(170, 290, 420, 30);

        upsuplrsubmitBtn.setText("DONE");
        upsuplrsubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upsuplrsubmitBtnActionPerformed(evt);
            }
        });
        jPanel2.add(upsuplrsubmitBtn);
        upsuplrsubmitBtn.setBounds(250, 380, 190, 50);

        addCus_notice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addCus_notice1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(addCus_notice1);
        addCus_notice1.setBounds(400, 580, 260, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Supplier ID:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 110, 140, 30);

        upsuplridT.setEditable(false);
        upsuplridT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(upsuplridT);
        upsuplridT.setBounds(170, 110, 420, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCusExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCusExitButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_addCusExitButton1ActionPerformed

    private void upsuplrmailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upsuplrmailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upsuplrmailTActionPerformed

    private void upsuplrsubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upsuplrsubmitBtnActionPerformed
        // TODO add your handling code here:
        String upsuplrid = upsuplridT.getText();
        String upsuplrname= upsuplrnameT.getText();
        String upsuplrmail = upsuplrmailT.getText();
        String upsuplrphn = upsuplrphnT.getText();
        
        if(upsuplrid.isEmpty() || upsuplrname.isEmpty() ||
                upsuplrmail.isEmpty() || upsuplrphn.isEmpty()){

            JOptionPane.showMessageDialog(null,"Please fill all fields");
        }
        else{
            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
                    + "databaseName=dbBOPMS;selectMethod=cursor", "sa", "123456");

                String sql = "Update supplier set supplierName="+upsuplrname+
                        " where supplierId = '"+upsuplrid+"'";
                PreparedStatement pst = connection.prepareStatement(sql);
                pst.executeUpdate();
                
                sql = "Update supplier set supplierMail="+upsuplrmail+
                        " where supplierId = '"+upsuplrid+"'";
                pst = connection.prepareStatement(sql);
                pst.executeUpdate();
                
                sql = "Update supplier set supplierPhone="+upsuplrphn+
                        " where supplierId = '"+upsuplrid+"'";
                pst = connection.prepareStatement(sql);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Updated Successfully!");
                suppliers suppliers = new suppliers();
                suppliers.setVisible(true);
                this.setVisible(false);


            } catch (ClassNotFoundException | SQLException e) {
            }
        }
    }//GEN-LAST:event_upsuplrsubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCusExitButton1;
    private javax.swing.JLabel addCus_notice1;
    private javax.swing.JLabel addcusLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField upsuplridT;
    private javax.swing.JTextField upsuplrmailT;
    private javax.swing.JTextField upsuplrnameT;
    private javax.swing.JTextField upsuplrphnT;
    private javax.swing.JButton upsuplrsubmitBtn;
    // End of variables declaration//GEN-END:variables
}
