/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbdummy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class updateCustomer extends javax.swing.JFrame {

    /**
     * Creates new form updateCustomer
     */
    
    public static String cusId = customers.cusid;
    public static String cusName = customers.cusname;
    public static String cusMail = customers.cusmail;
    public static String cusAddrss = customers.cusaddrss;
    public static String cusPhn = customers.cusphn;
    public static String cusTyp = customers.custyp;
    
    public updateCustomer() {
        initComponents();
        setCusInfo();
    }
    
    public void setCusInfo() {
        cusIdT.setText(cusId);
        cusNameT.setText(cusName);
        cusMailT.setText(cusMail);
        cusAddrssT.setText(cusAddrss);
        cusPhnT.setText(cusPhn);
        cusTypT.setText(cusTyp);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addcusLabel1 = new javax.swing.JLabel();
        updateCusExitButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cusNameT = new javax.swing.JTextField();
        cusMailT = new javax.swing.JTextField();
        cusAddrssT = new javax.swing.JTextField();
        cusPhnT = new javax.swing.JTextField();
        cusDoneBtn = new javax.swing.JButton();
        addCus_notice1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cusIdT = new javax.swing.JTextField();
        cusTypT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        backButtonIncome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(85, 104, 138));
        jPanel2.setLayout(null);

        addcusLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        addcusLabel1.setForeground(new java.awt.Color(255, 255, 255));
        addcusLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addcusLabel1.setText("Update Customer Info");
        jPanel2.add(addcusLabel1);
        addcusLabel1.setBounds(80, 0, 440, 40);

        updateCusExitButton.setBackground(new java.awt.Color(255, 255, 255));
        updateCusExitButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        updateCusExitButton.setText("X");
        updateCusExitButton.setMaximumSize(new java.awt.Dimension(10, 19));
        updateCusExitButton.setMinimumSize(new java.awt.Dimension(10, 19));
        updateCusExitButton.setPreferredSize(new java.awt.Dimension(10, 19));
        updateCusExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCusExitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(updateCusExitButton);
        updateCusExitButton.setBounds(560, 10, 60, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("NAME:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 130, 130, 30);

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("EMAIL:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 190, 130, 30);

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ADDRESS:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 250, 130, 30);

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("PHONE NO:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 310, 130, 30);
        jPanel2.add(cusNameT);
        cusNameT.setBounds(170, 130, 420, 30);

        cusMailT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusMailTActionPerformed(evt);
            }
        });
        jPanel2.add(cusMailT);
        cusMailT.setBounds(170, 190, 420, 30);
        jPanel2.add(cusAddrssT);
        cusAddrssT.setBounds(170, 250, 420, 30);
        jPanel2.add(cusPhnT);
        cusPhnT.setBounds(170, 310, 420, 30);

        cusDoneBtn.setText("DONE");
        cusDoneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusDoneBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cusDoneBtn);
        cusDoneBtn.setBounds(40, 430, 550, 50);

        addCus_notice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addCus_notice1.setForeground(new java.awt.Color(204, 0, 51));
        jPanel2.add(addCus_notice1);
        addCus_notice1.setBounds(400, 580, 260, 30);

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Customer ID:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 80, 140, 30);

        cusIdT.setEditable(false);
        cusIdT.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.add(cusIdT);
        cusIdT.setBounds(170, 80, 420, 30);
        jPanel2.add(cusTypT);
        cusTypT.setBounds(170, 360, 420, 30);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TYPE:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 360, 130, 30);

        backButtonIncome.setBackground(new java.awt.Color(255, 255, 255));
        backButtonIncome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        backButtonIncome.setText("<");
        backButtonIncome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backButtonIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonIncomeActionPerformed(evt);
            }
        });
        jPanel2.add(backButtonIncome);
        backButtonIncome.setBounds(0, 0, 60, 32);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(628, 512));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateCusExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCusExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_updateCusExitButtonActionPerformed

    private void cusMailTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusMailTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusMailTActionPerformed

    private void cusDoneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusDoneBtnActionPerformed
        // TODO add your handling code here:
        String cusId = cusIdT.getText();
        String cusname= cusNameT.getText();
        String cusMail = cusMailT.getText();
        String cusAddrss = cusAddrssT.getText();
        String cusPhn = cusPhnT.getText();
        String cusTyp = cusTypT.getText();

        if(cusId.isEmpty() || cusname.isEmpty() || cusMail.isEmpty() || cusAddrss.isEmpty() ||
            cusPhn.isEmpty() || cusTyp.isEmpty()){

            JOptionPane.showMessageDialog(null,"Please fill all fields");
        }
        else{
            try {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
                    + "databaseName=dbBOPMS;selectMethod=cursor", "sa", "123456");

                String sql = "Update customer set customerName='"+cusname+"',customerEmail='"+cusMail+
                        "',customerAddress='"+cusAddrss+"',customerPhone='"+cusPhn+
                        "',customerType='"+cusTyp+
                        "' where customerId = '"+cusId+"'";
                
                

                PreparedStatement pst = connection.prepareStatement(sql);

                pst.executeUpdate();

                //addCus_notice.setText("Customer is added Successfully");
                //dispose();
                cusIdT.setText("");
                cusNameT.setText("");
                cusMailT.setText("");
                cusAddrssT.setText("");
                cusPhnT.setText("");
                cusTypT.setText("");

            } catch (ClassNotFoundException | SQLException e) {
            }
        }
    }//GEN-LAST:event_cusDoneBtnActionPerformed

    private void backButtonIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonIncomeActionPerformed
        // TODO add your handling code here:
        customers customers = new customers();
        customers.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonIncomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCus_notice1;
    private javax.swing.JLabel addcusLabel1;
    private javax.swing.JButton backButtonIncome;
    private javax.swing.JTextField cusAddrssT;
    private javax.swing.JButton cusDoneBtn;
    private javax.swing.JTextField cusIdT;
    private javax.swing.JTextField cusMailT;
    private javax.swing.JTextField cusNameT;
    private javax.swing.JTextField cusPhnT;
    private javax.swing.JTextField cusTypT;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton updateCusExitButton;
    // End of variables declaration//GEN-END:variables
}
